### ISSUE TITLE
not found data_processing

### ISSUE THREAD

**Issue by utrobinmv** [IlyaGusev/saiga#1]
!python3 -m src.data_processing.compose_sft_dataset configs/datasets/sft_d4.json sft_d4_train.jsonl sft_d4_val.jsonl
python3: Error while finding module specification for 'src.data_processing.compose_sft_dataset' (ModuleNotFoundError: No module named 'src.data_processing')

**Comment by IlyaGusev** [comment]
Thank you, fixed
